name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (allowing no tests)
      - name: Run tests
        run: npm test -- --passWithNoTests

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t my-node-app .
